#!/bin/sh

SRC_DIR=$HOME/.xmonad
# The name of the executable produced by stack.
EXE_NAME=xmonad

# Are we on NixOS?
if nixos-version; then
    nixarg="--nix"
else
    nixarg=""
fi

stack_run() {
    if [ $1 != 0 ]; then
        stack="urxvt -e stack"
    else
        stack="stack"
    fi

    shift
    $stack $nixarg --stack-yaml=$SRC_DIR/stack.yaml $@
}

if [ ! -e $SRC_DIR/.stack-work ]; then
    stack_run 1 "setup"
fi

stack_run 1 "build"

EXE_DIR=$(stack_run 0 path --dist-dir)
$SRC_DIR/$EXE_DIR/build/$EXE_NAME/$EXE_NAME
