#!/bin/sh

XRANDR_RESET=

_xrandr() {
    xrandr --output DP-1 --off \
           --output eDP-1 --off \
           --output HDMI-1 --off

    xrandr $@
}

_finalize() {
    xsetroot -cursor_name arrow

    notify-send  "Environment switcher" "Enabled: $1"
}

desktop() {
    _xrandr --output DP-1 --auto --primary # --output eDP-1 --auto --same-as DP-1

    echo "Xft.dpi: 96" | xrdb -merge
    echo "Xcursor.size: 24" | xrdb -merge

    _finalize "Desktop (single monitor)"
}

laptop() {
    _xrandr --output eDP-1 --auto --primary

    echo "Xft.dpi: 192" | xrdb -merge
    echo "Xcursor.size: 48" | xrdb -merge

    _finalize "Laptop only"
}

case $1 in
    "desktop")
        desktop
        ;;
    "laptop")
        laptop
        ;;
esac
