#!/bin/sh

echo "Classifying…"

# Classify by inbox, don't untag new yet
notmuch tag +ac-amiens -- "tag:new and folder:/ac-amiens/"
notmuch tag +ac-orleans-tours -- "tag:new and folder:/ac-orleans-tours/"
notmuch tag +thb.lt -- "tag:new folder:/thb.lt/"

# inbox
notmuch tag +inbox -- "folder:/\\/Inbox$/"
notmuch tag -inbox -- "not folder:/\\/Inbox$/"

# drafts
notmuch tag +drafts -new -- "folder:/\\/Drafts$/"
notmuch tag -drafts -- "not folder:/\\/Drafts$/"

# sent
notmuch tag +sent -new -- "folder:/\\/Sent$/"
notmuch tag -sent -- "not folder:/\\/Sent$/"

# archive
notmuch tag +archive -new -- "folder:/\\/Archive$/"
notmuch tag -archive -- "not folder:/\\/Archive$/"

# deleted
notmuch tag +deleted -new -- "folder:/\\/Trash$/"
notmuch tag -deleted -- "not folder:/\\/Trash$/"

# spam
notmuch tag +spam -new -- "folder:/\\/Junk$/"
notmuch tag -spam -- "not folder:/\\/Junk$/"

# identify lost email
notmuch tag +lost -- "(not tag:sent) and (not tag:inbox) and (not tag:archive) and (not tag:draft) and (not tag:deleted)"
notmuch tag -lost -- "tag:lost and (tag:sent or tag:inbox or tag:archive or tag:draft or tag:deleted)"

notmuch search tag:inbox and tag:unread | wc -l > ~/.cache/unread-mail-count
echo Unread mail: $(cat ~/.cache/unread-mail-count)
