#!/bin/sh

set -e # Fail on error

# * Step1: sync folders

# notmuch search --output=files "tag:archive and !folder:/.*/Archive/"

# * Step2: fetch mail

gpg --card-status > /dev/null # Fail if card absent.
# ^ This so `notmuch new` can run in a background loop without
# endlessly prompting for a card if not present.
mbsync -a
