#+TITLE: Divers arch

* Powerbutton

/etc/systemd/logind.conf

See https://wiki.archlinux.org/index.php/Power_management#ACPI_events :

#+begin_quote 
  The specified action for each event can be one of ignore, poweroff, reboot, halt, suspend, hibernate, hybrid-sleep, lock or kexec. 
#+end_quote

Then =systemctl restart systemd-logind=

* Network manager and wired connections

Disable dhcpcd

* Java anti-aliasing

Add to /etc/environment

_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'

Other values for this setting can be found at https://wiki.archlinux.org/index.php/Java_Runtime_Environment_fonts#Anti-aliasing

* Printing
archlinux_printing.org
Install ghostscript manually.

AUR packages:
 brother-dcp7060d
 samsung-unified-driver
* Fix Macbook Air resume
It *seems* to work by simply adding acpi_osi=Darwin to kernel parameters.
* Fix Radeon flickering on the Mac Pro

Il y a un sous dossier avec un script et un service pour le lancer. 

* Macbook Air (and probably other apple devices) touchpad (multitouch)

 - *Don't* install =xf86-input-mtrack= neither the =-git= version.
 - BUT choose =xf86-input-libinput= for your input driver.  It knows gestures, but doesn't know what to do with them.  To test, run =libinput-debug-events=.  It should show swipe and pinch movements.
 - Install =libinput-gestures= from the AUR.  It requires =xdotool= to do anything with said gestures (or you may use anything else of course, but xdotool's cool and in official repos)
 - When asked, add yourself to group =input=.  Groups are cached: restart if needed.
 - Run =libinput-gestures-setup start=.
 - Configure =/etc/libinput-gestures.conf=
 - Rock and roll and swipe.
