#+TITLE: Notes on Debian
#+AUTHOR: thblt

Note to readers: Hi! You've just found a completely useless document.  This is my tutorial to install Debian the way I like it.  It won't be of any use to anyone else.

* Base install

Install Debian as usual.

 - Mirror :: Accept to configure a mirror on the network.  ftp.[country].debian.org is fine.
 - Popcon :: I usually decline.  Why is a different question.
 - Groups :: Ignore all packages groups *except the last one* (something like /Base system utilities/ or /Base Debian system/) , because I have *no f*ing idea* how to install it later.  It is the basic set of nice little system utilities (nano killall and stuff.).
 - Clock :: Accept to set hardware clock to UTC, because that's How It's Done.

* Post install

** Upgrade

 - Edit =/etc/apt/sources.list= (vi is installed):
   - Remove cdrom lines (gg5dd)
   - =%s/jessie/stretch/= (or whatever applies now.  You probably shouldn't stick with the current stable: unless the new stable is fresh and new, you'd better go for the next one.  There's gonna be trouble: this is install.  Better have problems once and for all with the current testing rather than with current stable and later, new stable.)
   - =%s/main/main contrib non-free=
 - =apt update=; =apt dist-upgrade=.  Coffee

** Belong in the cool groups

 - =usermod -aG sudo,adm,systemd-journal thblt=

** Install all the cool stuff

 - =apt install git=
 - as =thblt=, =git clone= your dotfiles to =~/.dotfiles=.
 - As root (you don't have sudo yet): =sh ~thblt/.dotfiles/bin/debian_base_install.sh=.  More coffee.  If you're on a slow connection, you may comment out texlive (but you're still going to get the gigabyte xmonad install)
 - As yourself, run =~/.dotfiles/bin/symlink_dotfiles.sh=
 - As yourself, =thblt_got_a_new_pc=.  It won't do much, but it will install Vundle and prevent vim from freaking out (and also create an empty .emacs.d/_customize.el).  (on Macs, it also installs Homebrew)  (Some day I may merge my various post-install scripts)
 - =chsh=, zsh is installed as =/usr/bin/zsh=.  The first zsh run will auto-install antigen which in turn will install its plugins, because of *magic* (and .zshrc)

*Reboot* to start working in Xorg.  Remember that in Debian, =sbin= is not in user's path: =$ reboot= will fail with command not found, but =sudo reboot= or =# reboot= works.

** Configure various system bits

*** Paramètres du noyau

Edit =/etc/default/grub=:

 - =libata.force=noncq= :: Évite les gels pénibles de SSD.
 - =acpi_osi=Darwin= :: Supposé régler les problèmes d'hibernation.
 
And run =update-grub=.

Note: *never* edit files under =/boot/=: they will be erased at next grub update.

*** Enable TRIM

- In =etc/cryptab=, add the =discard= option.
- In =/etc/lvm/lvm.conf=, set =issue_discards= to 1.
- TODO See Debian page: there's a system service template
- =sudo cp /usr/share/doc/util-linux/examples/fstrim.* /etc/systemd/system= (there should be two files: .service and .timer)
- =systemctl enable fstrim.timer=
- =sudo update-initramfs -u -k all=
  
*** Laptop

**** Wireless

Pour anna (MacBook Air 2011), =apt-get install firmware-brcm80211= devrait suffire à faire fonctionner le chip wifi.  Je n'ai pas regardé pour le bluetooth.  Si besoin, =sudo modprobe brcmsmac=.

**** Acpi

=systemctl enable acpid= + reboot

**** Apple keybard

Edit or create =/etc/modprobe.d/hid_apple.conf and add

#+begin_src 
options hid_apple fnmode=2
options hid_apple swap_opt_cmd=1
#+end_src

** Configure higher-level stuff

*** Dunst

In ArchLinux, dunst must be run by the user in some initialization script.  In Debian, for some reasons, it is started by the system while launching dbus. My =.xsessionrc= takes care of not running dunst on Debian.

*** LightDM

Edit =/etc/lightdm/lightdm.conf= and uncomment/set the following parameters:

#+begin_src
[Seat:*]
pam-service=lightdm
pam-autologin-service=lightdm-autologin
greeter-hide-users=false
autologin-user=thblt
exit-on-failure=true
#+end_src

Note: je trouve lightdm plus stable avec =pam.service=lightdm= décommenté.  C'est peut-être de la superstition, mais si ça évite de s'emmerder...

