* Emacs
** Changer la police d'un buffer
** M-x buffer-face-set [nom]
Rangé dans ~/.emacs
** Installer emacs cocoa avec fullscreen et tout
brew install emacs --cocoa --srgb
ln -s /usr/local/Cellar/emacs/24.2/Emacs.app /Applications/
Youpi
ns-toggle-fullscreen

Ce n'est pas un vrai fullscreen cocoa (24.2/9.0) mais c'est mieux en fait, hein.
** Tentative de folding automatique en LaTeX (AUCTeX)
*** Problème : avec Tex-fold-auto 1, insérer un \item avec C-c C-j provoque le repli immédiat de l'environnement autour, et empêche l'édition.
** Aide
C-h k — Trouver la commande associée à un raccourci
C-h m - Liste les commandes du mode actif (auctex dans ton cas) pratique comme aide mémoire
C-h f — permet de décrire une fonction (vaut mieux comprendre un peu le code elisp)
C-h i — passe dans le mode info, m AUCtex 
** TODO Assigner tab correctement
** TODO Réassigner meta sur alt
et attribuer les raccourcis nécessaires aux caractères qui utilisent alt : 
œ € - — – ®©™ \ … | [{}] 
(ou mieux, réassigner de façon plus intelligente {} et [] — que ça tire moins sur les doigts.
Du genre : M-q {, M-m }, M-s [, M-l ] pas mal pas mal
** TODO Voir s'il est possible et intéressant de faire taper la paire fermant/ouvrant en tapant le caractère ouvrant. ( => (|) (| = curseur). Normalement, c'est facile. 

* LaTeX
** Skim
*** L'auto-refresh cesse de fonctionner dans certains cas
Skim maintient un lien vers le fichier à la façon des applis MacOSX, lien qui est perdu quand le fichier est supprimé, ce qui est toujours le cas lors d'un (par ex.) *latexmk -gg fichier*. La meilleure solution est de faire tourner latexmk --pdf --pvc fichier. On peut créer un ~/.latexmkrc avec
$pdf_previewer = "open -a /Applications/Skim.app"; 
$clean_ext = "paux lox pdfsync out";
--pvc relance le build à la première modification d'un des fichiers manipulés par le build précédent (autrement dit, même si c'est un fichier appelé par input dans le principal
** Bibliographie
*** Titre
\renewcommand\contentsname{Titre}
Biblio sans titre : \defbibheading{bibliography}[\bibname]{}
** Table des matières
*** Changer le titre
\renewcommand{\contentsname}{Sommaire}
*Après* le \begin{document} où Babel s'initialise.
*** Supprimer le titre
Bête et méchant :

\makeatletter
\@starttoc{toc}
\makeatother
*** Plusieurs tables des matières
Peut-être une solution dans titletoc, mais sinon, la méthode interne de génération de la table : 
\@starttoc{toc}

semble prendre le nom du fichier en paramètre, on peut donc sans doute le combiner avec \addcontentsline pour générer plusieurs tocs et plusieurs fichiers
** \reversemarginpar
** Titlesec/titletoc
*** Titres en marge
\titleformat{\section}[leftmargin]
  {\singlespace\normalfont%
   %
   %\vspace{6pt}%
   \sffamily\filleft}
   	{\color{Gray}\thesection}{.5em}{\small\textbf}%
	\titlespacing{\section}%
  {3.5cm}{0cm}{.5cm}
*** Astérismes et pas de titre explicite
Appeler titlesec avec l'option [explicit] impose alors d'inclure #1 dans {before-code} (dernier param obligatoire) pour avoir le titre. Ce qui permet de s'en dispenser. Doc p. 4

Pour un sectionnement invisible dans le corps, par exemple :

\titleformat{\section}[wrap]{}{}{0cm}{}
\titlespacing{\section}{0pt}{0pt}{0pt}

C'est [wrap] qui semble garantir le mieux que la section ne créera pas d'espace blanc.

** \hfill
Pour le faire fonctionner même en début de ligne, utiliser la version étoilée d'\hspace, qui est gérée comme un caractère standard.
\\ \hspace{0cm}\hfill\hello, world! % Hello world à gauche
\\ \hspace*{0cm}\hfill\hello, world! % Hello world correctement ferré à droite
** geometry
% Depuis un export LyX
\usepackage[a4paper]{geometry}
\geometry{verbose,tmargin=2cm,bmargin=3cm,lmargin=4cm,rmargin=3cm}
** Paragraphes non indentés
\setlength{\parskip}{\smallskipamount}
\setlength{\parindent}{0pt} % LyX
** Citer avec origyear
À affiner, mais c'est l'idée :
\renewbibmacro*{cite:labelyear+extrayear}{%
\iffieldundef{labelyear}
{}
{\printtext[bibhyperref]{%
\iffieldundef{origyear}{}{\printfield{origyear}\addslash}%   <--- added
\printfield{labelyear}%
\printfield{extrayear}}}}

\renewbibmacro*{date+extrayear}{%
\iffieldundef{year}
{}
{\printtext[parens]{%
\iffieldundef{origyear}{}{\printfield{origyear}\addslash}%  <--- added
\printdateextra}}}
** Biber/BibLaTeX
*** Surcharger une référence (Shorthand par exemple)
Pour surcharger une référence de la bibliographie globale, il faut 
 - Créer un fichier de bibliographie local.
 - Reproduire la référence intégralement avec les modifs souhaitées.
 - Appeler ce fichier local avant le fichier global.
* Concordance entre les éditions des Dits et Écrits
DEI + 28 = DE1
DEII + 868 = DE1
DEIII = DE2
DEIV + 819 = DE2
* Trucs à lire (un jour)
** Sur le porno
Richard Dyer, /Male gay porn : coming to terms/ [Flo]
Thomas Waugh, /Men's pornography : gay vs straight/ (Jump Cut 1985)
** Sur la mort
Esquerre, Arnaud : /Les os, les cendres, l'État./
** Sur autre chose
Iakub, Marcela : /Le crime était presque sexuel/
* Mac
** Désactiver l'animation du plein écran à la con
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool NO
Faire reconnaître les frameworks OSX tiers à Eclipse:
Dans les réglages du projet, C/C++ General / Preprocessor include paths
Dans GNU C++:
Ajouter la racine (qui contient les bundle .Framework)
Et cocher "Contains sytem headers"
ça fait fonctionner les libraires Qt en tout cas
