theme = "onedark"

[editor]
line-number = "relative"
mouse = false
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
auto-signature-help = true
snippets = true

[keys.normal.space]
"H" = ":toggle lsp.display-inlay-hints"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal."«"]
"d" =  "goto_prev_diag"
"D" =  "goto_first_diag"
"g" =  "goto_prev_change"
"G" =  "goto_first_change"
"f" =  "goto_prev_function"
"t" =  "goto_prev_class"
"a" =  "goto_prev_parameter"
"c" =  "goto_prev_comment"
"T" =  "goto_prev_test"
"p" =  "goto_prev_paragraph"
"space" =  "add_newline_above"

[keys.normal."»"]
"d" = "goto_next_diag"
"D" = "goto_last_diag"
"g" = "goto_next_change"
"G" = "goto_last_change"
"f" = "goto_next_function"
"t" = "goto_next_class"
"a" = "goto_next_parameter"
"c" = "goto_next_comment"
"T" = "goto_next_test"
"p" = "goto_next_paragraph"
"space" = "add_newline_below"